-------------------------------Analise de relatorio tecnico------------------------------
SELECT
	VO1_FUNABE CODPRO,
	VO1_NUMOSV OS,
	CONVERT(DATE, ZO4_DATEXE) DATA,
	ZO4_CODPER CODPER,
	ZO4_TEXTO PERGUNTA,
CASE ZO4_RESPOS
	WHEN '0' THEN 'Nao'
	WHEN '1' THEN 'Sim'
	WHEN '2' THEN 'Nao se aplica'
ELSE 'Vazio'  END AVALIACAO_RELATORIO
FROM VO1010
	INNER JOIN VAI010 ON VO1_FUNABE = VAI_CODTEC AND VAI010.D_E_L_E_T_ = ''
	INNER JOIN ZO4010 ZO4 ON VO1_NUMOSV = ZO4_NUMOSV AND VO1_FILIAL = ZO4_FILIAL AND ZO4.D_E_L_E_T_ = ''
WHERE VO1010.D_E_L_E_T_=''
	AND ZO4_DATEXE >= '20231101'
GROUP BY VO1_FILIAL, VO1_FUNABE, VAI_NOMTEC, VO1_NUMOSV,ZO4_RESPOS, ZO4_CODPER, ZO4_DATEXE, ZO4_TEXTO