/*Requisições Oficina*/
SELECT 
	VO3_FILIAL AS FILIAL,
	'OFICINA' AS ORIGEM,
	VO3_CODITE AS CODIGO,
	VO3_QTDREQ AS QUANTIDADE,
	VO3_NUMOSV AS DOC,
	VAI_NOMTEC AS NOME,
	VAI_CODTEC AS COD_CONSULTOR,
	D3_CUSTO1 AS VALOR,
	CONVERT(DATE,VO2_DATREQ) DATA,
	--(select SUM(VB8_HITSB + VB8_HITSO + VB8_HITSI) FROM VB8010 WHERE DATEFROMPARTS(VB8_ANO,VB8_MES,VB8_DIA) BETWEEN CAST( DATEADD(MONTH,-12,GETDATE()) AS DATE ) AND CAST(GETDATE() AS DATE) AND VB8_PRODUT = VO3_CODITE AND VB8010.D_E_L_E_T_='') POPULARIDADE
	(SELECT COUNT(D2_COD)-SUM(CASE WHEN D2_QTDEDEV > 0 THEN 1 ELSE 0 END) FROM SD2010 D2  INNER JOIN SF4010 F4 ON D2_TES = F4_CODIGO     AND F4_OPEMOV = '05'    AND F4_ESTOQUE = 'S'       AND F4.D_E_L_E_T_ = ''     AND D2.D_E_L_E_T_ = '' WHERE D2_COD = VO3_CODITE  AND CONVERT(DATE,D2_EMISSAO) BETWEEN CAST( DATEADD(MONTH,-12,GETDATE()) AS DATE ) AND CAST(GETDATE() AS DATE) /* AND D2_FILIAL = B2_FILIAL*/) POPULARIDADE
  FROM VO3010 VO3
	  INNER JOIN VO2010 VO2 ON VO2_FILIAL = VO3_FILIAL AND VO2_NUMOSV = VO3_NUMOSV AND VO3_NOSNUM = VO2_NOSNUM  AND VO2.D_E_L_E_T_ = ''
	  INNER JOIN SD3010 D3 ON VO3_FILIAL = D3_FILIAL AND VO3_NUMDOC = D3_DOC AND D3_COD = VO3_CODITE AND D3_CF = 'RE4' AND D3.D_E_L_E_T_ = ''
	  INNER JOIN VAI010 VAI ON VO3_PROREQ = VAI_CODTEC AND VAI.D_E_L_E_T_ = ''
  WHERE 
  VO3.D_E_L_E_T_ = ''
  AND VO2_DEVOLU = '1'