/*Retrabalho*/
SELECT
VO1_FILIAL FILIAL, 
VO1_STATUS STATUS,
VO1_NUMOSV OS_CORRECAO,
CONVERT(DATE, VO1_DATABE) DATA,
VO1_FUNABE PRODUTIVO, 
VAI010.VAI_NOMTEC NOME,
CASE WHEN VO1_XOSRET <> '' THEN RIGHT('00000000'+TRIM(VO1_XOSRET),8) ELSE '        ' END OS_ORIGEM,   
CASE VO1_XRETRA WHEN '0' THEN 'NAO' 
                WHEN '1' THEN 'SIM'
                WHEN '' THEN 'Vazio' END RETRABALHO,  
ISNULL(VO4.VO4_DEPINT,'  ') DEPT_INTERNO,
ISNULL(X5_DESCRI,'                                                       ') DESCRICAO,
ISNULL(NOMTEC,'                              ') TECNICORETRABALHO,
ISNULL(CODPRO,'      ') CODPRO 
FROM VO1010
    INNER JOIN VAI010 ON VO1_FUNABE = VAI_CODTEC AND VAI010.D_E_L_E_T_ = ''
   LEFT JOIN (
	SELECT DISTINCT VO4_FILIAL, VO4_NUMOSV, VO4_DEPINT
	FROM VO4010
	WHERE D_E_L_E_T_ = ''
   ) VO4 ON VO4_NUMOSV = VO1_NUMOSV AND VO4_FILIAL = VO1_FILIAL
    LEFT JOIN SX5010 ON VO4_DEPINT = X5_CHAVE AND X5_TABELA = 'VD' AND SX5010.D_E_L_E_T_ = '' AND VO4_DEPINT = X5_CHAVE
    LEFT OUTER JOIN (
      SELECT DISTINCT
          VO4_FILIAL FILIAL, VO4_NUMOSV NUMOSV, VO4_CODPRO CODPRO,VAI_NOMTEC NOMTEC
        FROM VO4010 VO4
          INNER JOIN VAI010 VAI ON VO4_CODPRO = VAI_CODTEC AND VAI.D_E_L_E_T_ = ''
        WHERE VO4.D_E_L_E_T_ = '') AS OSRET ON OSRET.FILIAL = VO1_FILIAL AND OSRET.NUMOSV = RIGHT('00000000'+TRIM(VO1_XOSRET),8) AND VO1_XOSRET <> ''
WHERE VO1010.D_E_L_E_T_=''
AND VO1_STATUS <> 'C'
AND VO1_DATABE >= '20231101'